---
- name: Prometheus Installation
  hosts: local
  become: true
  tasks:
    - name: Download Alert manager
      get_url:
        url: https://github.com/prometheus/alertmanager/releases/download/v0.19.0/alertmanager-0.19.0.linux-amd64.tar.gz
        dest: /root

    - name: Untar the file
      unarchive:
        src: /root/alertmanager-0.19.0.linux-amd64.tar.gz
        dest: /root
        
    - name: Start Alert manager as a service, Copy the content of prometheus folder and paste it on /usr/local/bin/alertmanager folder
      shell: cp -r . /usr/local/bin/alertmanager
      args:
        chdir: /root/alertmanager-0.19.0.linux-amd64

    - name: Copy the service file and paste it /etc/systemd/system folder
      copy:
        src: /root/alertmanager.service
        dest: /etc/systemd/system
        owner: root
        group: root
        mode: 0644

    - name: Reload the daemon
      systemd: daemon_reload=yes

    - name: start the Prometheus service
      service:
        name: alertmanager
        state: started 
