---
# handlers file for Prometheus
   - name: Restart prometheus
     service:
        name: prometheus
        state: restarted

   - name: Restart node-exporter
     service:
        name: node-exporter
        state: restarted

   - name: Restart alertmanager
     service:
        name: alertmanager
        state: restarted

