global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_interval: 30s
  repeat_interval: 30s
  # Send all notifications to me.
  receiver: email-me
receivers:
- name: email-me
  email_configs:
  - send_resolved: true
    to: mail@gmail.com
    from: mail@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "mail@gmail.com"
    auth_identity: "mail@gmail.com"
    auth_password: "******"
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
