---
  - name: insert/update "Node-exporter" configuration block in /usr/local/bin/prometheus/prometheus.yml
    blockinfile:
      path: /usr/local/bin/prometheus/prometheus.yml
      backup: yes
      state: present
      create: yes
      block: |2
          - job_name: 'node-exporter'
            static_configs:
              - targets: ['localhost:9100']

  - name: Copy the Prometheus rules file and paste it in /usr/local/bin/prometheus folder
    copy:
      src: prometheus_rules.yml
      dest: /usr/local/bin/prometheus
      owner: root
      mode: 755

  - name: Change the working directory to /usr/local/bin/prometheus before executing the command. promtool with check the systex of the prometheus_rules.yml file
    shell: ./promtool check rules prometheus_rules.yml
    args:
      chdir: /usr/local/bin/prometheus
    register: rules_output

  - debug:
      var: rules_output

  - name: insert prometheus_rules.yml reference in the prometheus.yml file
    lineinfile:
      path: /usr/local/bin/prometheus/prometheus.yml
      insertafter: "rule_files:"
      line: '  - "prometheus_rules.yml"'
      state: present
    notify: Restart prometheus
