---
  - name: insert/update "alert-manager" configuration block in /usr/local/bin/prometheus/prometheus_rules.yml
    blockinfile:
      path: /usr/local/bin/prometheus/prometheus_rules.yml
      block: |2
          - name: alert_rules
            rules:
              - alert: InstanceDown
                expr: up == 0
                for: 10s
                labels:
                  severity: critical
                annotations:
                  summary: "Instance down"
                  description: "Instance has been down for more than 1 minute."

  - name: Use promtool to check the syntax of the prometheus_rules.yml file
    shell: ./promtool check rules prometheus_rules.yml
    args:
      chdir: /usr/local/bin/prometheus
    register: check_alertrule

  - name: Print the alertrule
    debug:
      var: check_alertrule

  - name: insert/update "Alertmanager" configuration block in /usr/local/bin/prometheus/prometheus.yml
    blockinfile:
      path: /usr/local/bin/prometheus/prometheus.yml
      backup: yes
      #marker: ""
      #insertafter: "#test_block"
      #insertafter: "# END ANSIBLE MANAGED BLOCK"
      block: |2
          - job_name: 'alertmanager'
            static_configs:
              - targets: ['localhost:9093']
    notify:
      - Restart prometheus
