---
  - name: Remove the alertmanager.yml file
    file:
      path: /usr/local/bin/alertmanager/alertmanager.yml
      state: absent

  - name: Copy the new config file from the present directory to the /usr/local/bin/alertmanager folder
    copy:
      src: alertmanager.yml
      dest: /usr/local/bin/alertmanager
      mode: 755
    notify:
      - Restart prometheus
      - Restart node-exporter

  - name: Check the syntax of config file
    shell: /usr/local/bin/alertmanager/amtool check-config /usr/local/bin/alertmanager/alertmanager.yml
    args:
      chdir: /usr/local/bin/alertmanager

  - name: Enable alertmanager as target in /usr/local/bin/promtheus/promentheus.yml file
    lineinfile:
      path: /usr/local/bin/prometheus/prometheus.yml
      insertafter: "# - alertmanager:9093"
      line: |9
                           - localhost:9093
    notify:
      - Restart prometheus
      - Restart alertmanager
