---
  - name: Download Blackbox exporter
    get_url: 
      url: https://github.com/prometheus/blackbox_exporter/releases/download/v0.19.0/blackbox_exporter-0.19.0.linux-amd64.tar.gz
      dest: /root

  - name: Untar the file
    unarchive:
      src: /root/blackbox_exporter-0.19.0.linux-amd64.tar.gz
      dest: /root

  - name: Create blackbox_exporter folder
    file:
      path: /usr/local/bin/blackbox_exporter
      owner: root
      group: root
      mode: '0644'
      state: directory

  - name: Copy content from /root/blackbox_exporter-0.19.0.linux-amd64
    copy:
      src: "{{ item }}"
      dest: /usr/local/bin/blackbox_exporter
      mode: 0644
    with_items:
      - /root/blackbox_exporter-0.19.0.linux-amd64/blackbox_exporter
      - /root/blackbox_exporter-0.19.0.linux-amd64/blackbox.yml

  - name: Copy the service file and paste it /etc/systemd/system folder
    copy:
      src: blackbox-exporter.service
      dest: /etc/systemd/system
      owner: root
      group: root
      mode: 0644

  - name: Reload the daemon
    systemd: daemon_reload=yes

  - name: Set blackbox as target
    blockinfile:
      path: /usr/local/bin/prometheus/prometheus.yml
      backup: yes
      state: present
      marker: ""
      insertafter: "  - targets: ['0.0.0.0:9323']"
      block: |2
          - job_name: 'blackbox'
            metrics_path: /probe
            params:
              module: [http_2xx]  # Look for a HTTP 200 response.
            static_configs:
              - targets:
                 - http://thinknyx.com # Target to probe with http on port 8080.
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: 0.0.0.0:9115  # The blackbox exporter's real hostname:port.
