---
  - name: Download Alert manager
    get_url:
      url: https://github.com/prometheus/alertmanager/releases/download/v0.19.0/alertmanager-0.19.0.linux-amd64.tar.gz
      dest: /root

  - name: Untar the file
    unarchive:
      src: /root/alertmanager-0.19.0.linux-amd64.tar.gz
      dest: /root

  - name: Copy the content of /alertmanager-0.19.0.linux-amd64 folder to alertmanager
    command: cp -r . /usr/local/bin/alertmanager
    args:
      chdir: /root/alertmanager-0.19.0.linux-amd64
    ignore_errors: yes

  - name: Copy the service file and paste it /etc/systemd/system folder
    copy:
      src: alertmanager.service
      dest: /etc/systemd/system
      owner: root
      group: root
      mode: 0644

  - name: Reload the daemon
    systemd: daemon_reload=yes
    notify: Restart alertmanager
