---
  - name: Download Prometheus
    get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.30.0/prometheus-2.30.0.linux-amd64.tar.gz
      dest: /root

  - name: Untar the file
    unarchive:
      src: /root/prometheus-2.30.0.linux-amd64.tar.gz
      dest: /root
        
  - name: Start Prometheus as a service, Copy the content of prometheus folder and paste it on /usr/local/bin folder
    copy:
      src: /root/prometheus-2.30.0.linux-amd64/
      dest: /usr/local/bin/prometheus
      owner: root
      group: root
      mode: 0755

  - name: Copy the service file and paste it /etc/systemd/system folder
    copy:
      src: prometheus.service
      dest: /etc/systemd/system
      owner: root
      group: root
      mode: 0644

  - name: Reload the daemon
    systemd: daemon_reload=yes
    notify: Restart prometheus
