  - name: insert/update "Node-exporter" configuration block in /usr/local/bin/prometheus/prometheus.yml
    blockinfile:
      path: /usr/local/bin/prometheus/prometheus.yml
      backup: yes
      state: present
      insertafter: '      - targets: ["localhost:9090"]'
      block: |2
          - job_name: 'node-exporter'
            static_configs:
              - targets: ['localhost:9100']
